### ISSUE TITLE
maven repo doesnt match the github code

### ISSUE THREAD

**Issue by firecode9** [petercipov/traces#2]
Hi,
Trying to use it but the github code doesnt match the maven repo.

Any idea why ?

**Comment by petercipov** [comment]
Hello,
you probably see differences because in maven repo there is an older version 1.0, and in master there is current devel.

sources for 1.0 are here https://github.com/petercipov/traces/tree/v1.0.0

**Comment by firecode9** [comment]
I see.
any idea when the master will be pushed to the maven repo ?

**Comment by petercipov** [comment]
now ;-)

**Comment by firecode9** [comment]
Hey, 
BTW, the maven repo have just version 1.0.0

**Comment by petercipov** [comment]
strange I am pretty sure I have put it to sonatype repo ... I will check it

**Comment by petercipov** [comment]
Done. It is already in oss sonatype release repo. In central it will be synced in couple of hours.
